//! Phase 0.2 safety net: generate `apps/flowstate/src/lib/generated/types.ts`
//! from the Rust wire types in `provider-api`. The file is committed to
//! the repo; CI runs this test then `git diff --exit-code` on the
//! generated dir to catch Rust↔TS drift the moment it lands.
//!
//! **To regenerate:**
//! `cargo test -p zenui-provider-api --features ts-bindings --test ts_bindings`.
//!
//! Types not exported here are either (a) purely adapter-internal
//! (`ProviderTurnEvent`, `TurnEventSink`) or (b) trivial payloads that
//! don't appear in frontend code (`HealthPayload`). Adding a new wire
//! type: append it below and re-run the test.

#![cfg(feature = "ts-bindings")]

use ts_rs::{Config, TS};
use zenui_provider_api::*;

/// Emits `export <decl>` with a trailing blank line.
fn push(out: &mut String, decl: String) {
    out.push_str("export ");
    out.push_str(&decl);
    out.push_str("\n\n");
}

#[test]
fn export_ts_bindings() {
    // Map Rust `u64`/`i64`/`u128`/`i128` to `number` (not `bigint`), matching
    // the existing frontend contract — the TS consumers of `token_count`,
    // `duration_ms`, etc. all treat these as regular JS numbers. If a field
    // ever genuinely exceeds 2^53 we'd switch it to a string on both sides;
    // that's an explicit schema change rather than silent behavior drift.
    let cfg = Config::default().with_large_int("number");
    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo test -p zenui-provider-api --features ts-bindings --test ts_bindings`.\n",
    );
    out.push_str("// Source of truth: crates/core/provider-api/src/lib.rs.\n");
    out.push_str("// DO NOT EDIT — run the test to regenerate.\n\n");

    // `serde_json::Value` → ts-rs emits the literal name `JsonValue`.
    // Define it once here so the generated file is self-contained.
    out.push_str("export type JsonValue = unknown;\n\n");

    // ---- enums -----------------------------------------------------
    push(&mut out, ProviderKind::decl(&cfg));
    push(&mut out, ProviderStatusLevel::decl(&cfg));
    push(&mut out, SessionStatus::decl(&cfg));
    push(&mut out, TurnStatus::decl(&cfg));
    push(&mut out, ToolCallStatus::decl(&cfg));
    push(&mut out, PermissionDecision::decl(&cfg));
    push(&mut out, PermissionMode::decl(&cfg));
    push(&mut out, ReasoningEffort::decl(&cfg));
    push(&mut out, FileOperation::decl(&cfg));
    push(&mut out, SubagentStatus::decl(&cfg));
    push(&mut out, PlanStatus::decl(&cfg));
    push(&mut out, SkillSource::decl(&cfg));
    push(&mut out, CompactTrigger::decl(&cfg));
    push(&mut out, MemoryRecallMode::decl(&cfg));
    push(&mut out, MemoryRecallScope::decl(&cfg));
    push(&mut out, RateLimitStatus::decl(&cfg));
    push(&mut out, TurnPhase::decl(&cfg));

    // ---- leaf structs ---------------------------------------------
    push(&mut out, PlanStep::decl(&cfg));
    push(&mut out, PlanRecord::decl(&cfg));
    push(&mut out, FileChangeRecord::decl(&cfg));
    push(&mut out, SubagentRecord::decl(&cfg));
    push(&mut out, MemoryRecallItem::decl(&cfg));
    push(&mut out, ContextCategory::decl(&cfg));
    push(&mut out, ContextBreakdown::decl(&cfg));
    push(&mut out, ToolCall::decl(&cfg));
    push(&mut out, TokenUsage::decl(&cfg));
    push(&mut out, RateLimitInfo::decl(&cfg));

    // ---- user-input -----------------------------------------------
    push(&mut out, UserInputOption::decl(&cfg));
    push(&mut out, UserInputQuestion::decl(&cfg));
    push(&mut out, UserInputAnswer::decl(&cfg));

    // ---- attachments ----------------------------------------------
    push(&mut out, ImageAttachment::decl(&cfg));
    push(&mut out, AttachmentRef::decl(&cfg));
    push(&mut out, AttachmentData::decl(&cfg));

    // ---- catalog --------------------------------------------------
    push(&mut out, ProviderModel::decl(&cfg));
    push(&mut out, ProviderFeatures::decl(&cfg));
    push(&mut out, ProviderStatus::decl(&cfg));
    push(&mut out, CommandKind::decl(&cfg));
    push(&mut out, ProviderCommand::decl(&cfg));
    push(&mut out, ProviderAgent::decl(&cfg));
    push(&mut out, McpServerInfo::decl(&cfg));
    push(&mut out, CommandCatalog::decl(&cfg));

    // ---- sessions / projects --------------------------------------
    push(&mut out, ProjectRecord::decl(&cfg));
    push(&mut out, SessionSummary::decl(&cfg));
    push(&mut out, ProviderSessionState::decl(&cfg));
    push(&mut out, TurnRecord::decl(&cfg));
    push(&mut out, SessionDetail::decl(&cfg));
    push(&mut out, AppSnapshot::decl(&cfg));
    push(&mut out, BootstrapPayload::decl(&cfg));

    // ---- content blocks ------------------------------------------
    push(&mut out, ContentBlock::decl(&cfg));

    // ---- wire envelopes ------------------------------------------
    push(&mut out, RuntimeEvent::decl(&cfg));
    push(&mut out, ClientMessage::decl(&cfg));
    push(&mut out, ServerMessage::decl(&cfg));

    // Target: apps/flowstate/src/lib/generated/types.ts (committed).
    let target = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../../apps/flowstate/src/lib/generated/types.ts");
    std::fs::create_dir_all(target.parent().unwrap())
        .expect("create generated dir");
    std::fs::write(&target, out).expect("write generated types.ts");
}
