//! Generate `spec_types.rs` from the committed opencode `/doc`
//! OpenAPI snapshot.
//!
//! Why a hand-rolled generator instead of `progenitor`? Opencode's
//! spec is OpenAPI **3.1.1**, which `openapiv3` (the parser
//! `progenitor` builds on) doesn't accept — 3.1 added features like
//! `propertyNames` and `const` that 3.0 can't represent. Our spec
//! is also tiny (5 schema components, 3 operations as of 1.14.41), so
//! the cost of writing a focused generator is far less than the cost
//! of patching the spec down to 3.0 every build.
//!
//! We support exactly the schema shapes that appear in the live
//! opencode spec today:
//!
//! - `object` with `properties` + `required` (+ optional
//!   `additionalProperties`)
//! - `anyOf: [{$ref}, ...]` (tagged union via the `type` discriminator)
//! - field types: `string`, `boolean`, `integer`, untyped (`{}` →
//!   `serde_json::Value`), and inline objects with
//!   `additionalProperties` (rendered as
//!   `std::collections::BTreeMap<String, serde_json::Value>`).
//!
//! When opencode adds a new schema shape we don't recognise here, the
//! generator panics with the offending JSON path so the build fails
//! loudly rather than emitting subtly-wrong types. Update this file
//! to support the new shape; do **not** update `spec_types.rs` by
//! hand — it's overwritten on every build.
//!
//! Spec snapshot lives at `tests/fixtures/openapi-<VERSION>.json`.
//! Bump `SPEC_PATH` below when re-baselining; see
//! `CLAUDE.md::Verify feature parity` for the runbook.

use serde_json::Value;
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::Path;

/// Path to the committed OpenAPI snapshot, relative to the crate root.
/// Bump on re-baseline.
const SPEC_PATH: &str = "tests/fixtures/openapi-1.14.41.json";

fn main() {
    println!("cargo:rerun-if-changed={SPEC_PATH}");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let spec_path = Path::new(&manifest_dir).join(SPEC_PATH);
    let spec_text = fs::read_to_string(&spec_path)
        .unwrap_or_else(|e| panic!("read spec at {}: {e}", spec_path.display()));
    let spec: Value = serde_json::from_str(&spec_text)
        .unwrap_or_else(|e| panic!("parse spec at {}: {e}", spec_path.display()));

    let info_version = spec
        .pointer("/info/version")
        .and_then(Value::as_str)
        .unwrap_or("unknown");
    let openapi_version = spec
        .pointer("/openapi")
        .and_then(Value::as_str)
        .unwrap_or("unknown");

    let mut out = String::new();
    out.push_str(&format!(
        "// @generated by build.rs — DO NOT EDIT BY HAND.\n\
         // Source: {SPEC_PATH}\n\
         // OpenAPI version: {openapi_version}\n\
         // info.version:    {info_version}\n\
         //\n\
         // Regenerate by re-running `cargo build` after refreshing the\n\
         // committed `/doc` fixture; the build script picks the file up\n\
         // automatically (see `cargo:rerun-if-changed` directives in\n\
         // `build.rs`). Update `build.rs::SPEC_PATH` when bumping to a\n\
         // newer opencode version.\n\n"
    ));

    out.push_str("use serde::{Deserialize, Serialize};\n");
    out.push_str("use std::collections::BTreeMap;\n\n");

    // Emit a small constant block with version metadata so callers can
    // assert what the runtime expects.
    out.push_str(&format!(
        "/// OpenAPI document version reported by `info.version` in the\n\
         /// snapshot this module was generated from.\n\
         pub const OPENAPI_INFO_VERSION: &str = \"{info_version}\";\n\n\
         /// OpenAPI specification version (e.g. \"3.1.1\").\n\
         pub const OPENAPI_VERSION: &str = \"{openapi_version}\";\n\n"
    ));

    let schemas = spec
        .pointer("/components/schemas")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();

    // Pre-pass: figure out which schemas are referenced from an
    // `anyOf` union whose every variant declares a `type` field with
    // a unique `const`. Those variants get the `type` field stripped
    // from their struct definitions, because the parent enum will
    // re-add it via `#[serde(tag = "type")]` discriminator routing.
    //
    // Without this, untagged-anyOf decoding silently picks the first
    // variant whose required fields all happen to be present —
    // e.g. an `ApiAuth` impostor swallowing a `WellKnownAuth` payload.
    let discriminated_variants = find_discriminated_variants(&schemas);

    // Stable ordering: schema name -> generated code.
    let ordered: BTreeMap<_, _> = schemas.into_iter().collect();
    for (name, schema) in ordered {
        let code = emit_schema(&name, &schema, &discriminated_variants);
        out.push_str(&code);
        out.push('\n');
    }

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let out_path = Path::new(&out_dir).join("spec_types.rs");
    fs::write(&out_path, &out)
        .unwrap_or_else(|e| panic!("write generated file {}: {e}", out_path.display()));
}

/// Map of variant-name -> (parent-union-name, const-discriminator).
/// Computed once up front so we can strip the `type` field from
/// variant structs and emit a tagged-enum parent.
type DiscriminatedVariants = BTreeMap<String, (String, String)>;

/// Walk every top-level schema looking for `anyOf: [{$ref}, ...]`
/// patterns where each referenced object has a required `type`
/// property declaring a `const` string. Those are tagged unions.
fn find_discriminated_variants(
    schemas: &serde_json::Map<String, Value>,
) -> DiscriminatedVariants {
    let mut out: DiscriminatedVariants = BTreeMap::new();
    for (parent_name, schema) in schemas {
        let Some(any_of) = schema.get("anyOf").and_then(Value::as_array) else {
            continue;
        };
        let variants: Vec<&str> = any_of
            .iter()
            .filter_map(|v| v.get("$ref").and_then(Value::as_str))
            .filter_map(|r| r.rsplit('/').next())
            .collect();
        if variants.len() != any_of.len() {
            continue; // not a clean anyOf-of-refs union
        }
        let mut tags: Vec<(String, String)> = Vec::with_capacity(variants.len());
        let mut all_have_const = true;
        for variant in &variants {
            let Some(target) = schemas.get(*variant) else {
                all_have_const = false;
                break;
            };
            let const_value = target
                .pointer("/properties/type/const")
                .and_then(Value::as_str);
            match const_value {
                Some(c) => tags.push((variant.to_string(), c.to_string())),
                None => {
                    all_have_const = false;
                    break;
                }
            }
        }
        if !all_have_const {
            continue;
        }
        for (variant, tag) in tags {
            out.insert(variant, (parent_name.clone(), tag));
        }
    }
    out
}

/// Emit a top-level Rust definition for a schema component.
fn emit_schema(
    name: &str,
    schema: &Value,
    discriminated: &DiscriminatedVariants,
) -> String {
    if let Some(any_of) = schema.get("anyOf").and_then(Value::as_array) {
        return emit_any_of(name, any_of, schema);
    }
    if let Some(ty) = schema.get("type").and_then(Value::as_str) {
        if ty == "object" {
            // If this struct is a variant of a discriminated union, the
            // parent enum carries the `type` tag — strip it from this
            // struct so serde's `tag = "type"` doesn't see it twice.
            let strip_type = discriminated.contains_key(name);
            return emit_object(name, schema, strip_type);
        }
    }
    panic!(
        "build.rs: unsupported top-level schema shape for `{name}`. \
         Update `emit_schema` in build.rs to handle: {schema}"
    );
}

/// Emit an `enum` for an `anyOf` of `$ref`s.
///
/// When every variant has a `type: { const: "..." }` discriminator
/// (the OpenAPI 3.1 idiom for tagged unions), emit a serde
/// `tag = "type"` enum so dispatch is exact. Otherwise fall back to
/// `untagged` — which is brittle for overlapping shapes but matches
/// what the spec is actually asking for.
fn emit_any_of(name: &str, variants: &[Value], _schema: &Value) -> String {
    // Re-derive the per-variant tag (yes, we computed this in
    // `find_discriminated_variants`, but the union-side perspective is
    // tiny and self-contained).
    let mut variant_tags: Vec<(String, Option<String>)> = Vec::with_capacity(variants.len());
    for v in variants {
        let r = v
            .get("$ref")
            .and_then(Value::as_str)
            .unwrap_or_else(|| panic!("anyOf variant in `{name}` is not a $ref: {v}"));
        let target = r
            .rsplit('/')
            .next()
            .unwrap_or_else(|| panic!("malformed $ref `{r}` in `{name}`"))
            .to_string();
        // `_schema` doesn't carry resolved refs; the tag (if any) was
        // already pre-computed and is rebuilt below from the spec.
        variant_tags.push((target, None));
    }

    let tagged: Option<Vec<(String, String)>> = compute_anyof_tags(variants);

    let mut out = String::new();
    out.push_str(&format!(
        "/// Generated from `components.schemas.{name}` (anyOf union).\n"
    ));
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]\n");
    if tagged.is_some() {
        out.push_str("#[serde(tag = \"type\")]\n");
    } else {
        out.push_str("#[serde(untagged)]\n");
    }
    out.push_str(&format!("pub enum {name} {{\n"));
    if let Some(tags) = tagged {
        for (variant, tag) in tags {
            out.push_str(&format!("    #[serde(rename = \"{tag}\")]\n"));
            out.push_str(&format!("    {variant}({variant}),\n"));
        }
    } else {
        for (variant, _) in variant_tags {
            out.push_str(&format!("    {variant}({variant}),\n"));
        }
    }
    out.push_str("}\n");
    out
}

/// If every variant in `variants` resolves through its `$ref` against
/// the spec we already loaded, this returns `Some(vec)` of
/// (variant-name, const-tag); otherwise `None`. We recompute it from
/// the snapshot's components map for parity with
/// `find_discriminated_variants`.
fn compute_anyof_tags(variants: &[Value]) -> Option<Vec<(String, String)>> {
    // Re-read the spec from disk; cheap because build.rs already
    // bound `SPEC_PATH` in main(), and the file is small.
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").ok()?;
    let spec_text = fs::read_to_string(Path::new(&manifest_dir).join(SPEC_PATH)).ok()?;
    let spec: Value = serde_json::from_str(&spec_text).ok()?;
    let schemas = spec.pointer("/components/schemas")?.as_object()?;
    let mut out = Vec::with_capacity(variants.len());
    for v in variants {
        let r = v.get("$ref")?.as_str()?;
        let name = r.rsplit('/').next()?.to_string();
        let target = schemas.get(&name)?;
        let tag = target
            .pointer("/properties/type/const")
            .and_then(Value::as_str)?
            .to_string();
        out.push((name, tag));
    }
    Some(out)
}

/// Emit a `struct` for an `object` schema with `properties`. When
/// `strip_type` is true, the `type` discriminator field is omitted —
/// see `find_discriminated_variants` for the rationale.
fn emit_object(name: &str, schema: &Value, strip_type: bool) -> String {
    let properties = schema
        .get("properties")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();
    let required: Vec<String> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|a| {
            a.iter()
                .filter_map(|v| v.as_str().map(str::to_string))
                .collect()
        })
        .unwrap_or_default();

    let mut out = String::new();
    out.push_str(&format!(
        "/// Generated from `components.schemas.{name}` (object).\n"
    ));
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]\n");
    out.push_str(&format!("pub struct {name} {{\n"));

    // Stable field ordering.
    let ordered: BTreeMap<_, _> = properties.into_iter().collect();
    for (field, prop) in ordered {
        // Discriminated-variant structs skip their own `type` field
        // because the parent `#[serde(tag = "type")]` enum owns it.
        if strip_type && field == "type" {
            continue;
        }
        let is_required = required.iter().any(|r| r == &field);
        let mut rust_ty = rust_type_for(&prop, &format!("{name}.{field}"));
        if !is_required {
            rust_ty = format!("Option<{rust_ty}>");
        }

        // Field name handling. Three concerns:
        //   1. Rust keyword collisions (`type`, `ref`, `self`, `match`)
        //      need `r#` prefixes.
        //   2. camelCase JSON fields (e.g. `accountId`) want snake_case
        //      Rust names (`account_id`) plus a `#[serde(rename)]`.
        //   3. Plain snake_case fields pass through unchanged.
        let snake = to_snake_case(&field);
        let needs_rename = snake != field;
        let is_keyword = matches!(field.as_str(), "type" | "ref" | "self" | "match");
        let (rust_name, attr) = if is_keyword {
            (
                format!("r#{field}"),
                Some(format!("    #[serde(rename = \"{field}\")]\n")),
            )
        } else if needs_rename {
            (
                snake,
                Some(format!("    #[serde(rename = \"{field}\")]\n")),
            )
        } else {
            (field.clone(), None)
        };

        // Document the `const` discriminator so the `Auth` untagged
        // enum's tag mapping is obvious in rustdoc.
        if let Some(c) = prop.get("const").and_then(Value::as_str) {
            out.push_str(&format!(
                "    /// Const discriminator: `\"{c}\"`.\n"
            ));
        }
        if !is_required {
            out.push_str("    #[serde(skip_serializing_if = \"Option::is_none\", default)]\n");
        }
        if let Some(a) = attr {
            out.push_str(&a);
        }
        out.push_str(&format!("    pub {rust_name}: {rust_ty},\n"));
    }
    out.push_str("}\n");
    out
}

/// Convert a camelCase JSON field name into snake_case for Rust. We
/// intentionally keep this simple: insert an underscore before each
/// uppercase letter that follows a lowercase letter or digit, then
/// lowercase everything. Acronyms (`URL`, `ID`) end up as
/// `url`/`id` rather than `u_r_l`/`i_d` because the input from
/// opencode's spec uses `Url` / `Id` patterns (e.g. `enterpriseUrl`,
/// `accountId`), not `enterpriseURL`.
fn to_snake_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    let mut prev_lower_or_digit = false;
    for c in s.chars() {
        if c.is_ascii_uppercase() {
            if prev_lower_or_digit {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
            prev_lower_or_digit = false;
        } else {
            out.push(c);
            prev_lower_or_digit = c.is_ascii_lowercase() || c.is_ascii_digit();
        }
    }
    out
}

/// Map a JSON-Schema fragment onto a Rust type. The `path` argument
/// is just for error messages.
fn rust_type_for(prop: &Value, path: &str) -> String {
    // Untyped (`{}`) — escape hatch for free-form payloads.
    if prop.as_object().map(|o| o.is_empty()).unwrap_or(false) {
        return "serde_json::Value".to_string();
    }
    if let Some(r) = prop.get("$ref").and_then(Value::as_str) {
        return r
            .rsplit('/')
            .next()
            .unwrap_or_else(|| panic!("malformed $ref `{r}` at {path}"))
            .to_string();
    }
    let ty = prop
        .get("type")
        .and_then(Value::as_str)
        .unwrap_or_else(|| panic!("schema at {path} is missing `type` and `$ref`: {prop}"));
    match ty {
        "string" => "String".to_string(),
        "boolean" => "bool".to_string(),
        "integer" => "i64".to_string(),
        "number" => "f64".to_string(),
        "array" => {
            let items = prop
                .get("items")
                .unwrap_or_else(|| panic!("array at {path} missing `items`"));
            let inner = rust_type_for(items, &format!("{path}.items"));
            format!("Vec<{inner}>")
        }
        "object" => {
            // Map-ish object (additionalProperties present, no fixed
            // properties) → BTreeMap<String, V>. Otherwise fall back
            // to Value to keep the generator focused on shapes the
            // spec actually uses today.
            let has_props = prop
                .get("properties")
                .and_then(Value::as_object)
                .map(|p| !p.is_empty())
                .unwrap_or(false);
            if has_props {
                panic!(
                    "build.rs: inline objects with named `properties` are not supported at {path}. \
                     Either lift to a top-level component or extend `rust_type_for`."
                );
            }
            if let Some(ap) = prop.get("additionalProperties") {
                let inner = if ap.as_object().map(|o| o.is_empty()).unwrap_or(false) {
                    "serde_json::Value".to_string()
                } else {
                    rust_type_for(ap, &format!("{path}.additionalProperties"))
                };
                format!("BTreeMap<String, {inner}>")
            } else {
                "serde_json::Value".to_string()
            }
        }
        other => panic!("unsupported JSON-schema type `{other}` at {path}: {prop}"),
    }
}
